spring:
  application:
    name: saju
  config:
    import: secrets.yml

  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none   #첫번째는 create 두번째는 none
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never    #첫번째는 always 두번째는 never
logging:
  level:
    org.hibernate.engine.jdbc.env.internal: DEBUG
    org.hibernate.engine.jdbc.connections.internal: DEBUG
    com.zaxxer.hikari: DEBUG